### ISSUE TITLE
Jabber Window not in "Space" in the Forefront Causes Fault

### ISSUE THREAD

**Issue by dusty81** [dusty81/MacJabberBlync#1]
If the main Jabber window is on the desktop space is not the active space, the program crashes.  

`
Traceback (most recent call last):
  File "./jabber_status_watch.py", line 54, in <module>
    light.color= Light_Color
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/blynclight/blynclight.py", line 313, in __setattr__
    super().__setattr__(name, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/blynclight/blynclight.py", line 393, in color
    self.red, self.blue, self.green = newValue[:3]
TypeError: 'NoneType' object is not subscriptable
`

**Comment by dusty81** [comment]
saw if catching this error is enough.  Fixed.
