### ISSUE TITLE
Catch Exception for when light is unplugged while script is running

### ISSUE THREAD

**Issue by dusty81** [dusty81/MacJabberBlync#3]
An exception is thrown when the light is unplugged while the program is running.  Should catch the exception, print output and then keep re-trying.  Useful for a laptop that might leave a desk and come back / etc.

**Comment by dusty81** [comment]
Traceback (most recent call last):
  File "/Users/Home/Git/MacJabberBlync/jabber_status_watch.py", line 71, in <module>
    light.on = True
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/blynclight/blynclight.py", line 313, in __setattr__
    super().__setattr__(name, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/blynclight/blynclight.py", line 403, in on
    self.off = 0 if newValue else 1
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/blynclight/blynclight.py", line 317, in __setattr__
    raise IOError(f"wrote {n} bytes, expected {len(self.bytes)} bytes")
OSError: wrote -1 bytes, expected 9 bytes
